### ISSUE TITLE
Adding Logo 

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#1]
Adding a logo in the side nav from the assets folder.
Also adding a logo in the about app page

**Comment by Vrushti24** [comment]
I would love to contribute in this!!

**Comment by anushbhatia** [comment]
logos are added to assets folder if you need pngs for it ping me on slack

**Comment by chehak123** [comment]
I would like to work on this issue under DWoc.

**Comment by smaranjitghose** [comment]
> I would like to work on this issue under DWoc.

Please wait for 2 more days till @Vrushti24 gives a PR.

**Comment by himanshu007-creator** [comment]
please assign me this issue

**Comment by Vrushti24** [comment]
@smaranjitghose I have already completed adding logos and u have unassigned me now I said u that i was having my classes so u said no problem now what should  I do?

**Comment by smaranjitghose** [comment]
> @smaranjitghose I have already completed adding logos and u have unassigned me now I said u that i was having my classes so u said no problem now what should I do?

Yes I remember, You can still go ahead with the PR within next 3 days.

**Comment by Vrushti24** [comment]
okay I will do PR today.

**Comment by himanshu007-creator** [comment]
@smaranjitghose sir pr sent , i have added logo file.https://github.com/smaranjitghose/DocLense/pull/15

**Comment by Vrushti24** [comment]
PR #16 added check it out.

**Comment by Vrushti24** [comment]
I have updated PR #16 please check that out

**Comment by Vrushti24** [comment]
@smaranjitghose  I am not able to close this issue how can close this my PR was successfully merged
