### ISSUE TITLE
PDF with no borders

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#100]
Currently, the pdf formed is having white spaces in it. Improving it by only representing the size of the image as a particular page in the pdf formed.
![image](https://user-images.githubusercontent.com/40017559/107608594-6a3e6180-6c62-11eb-9af3-5deb0016062a.png)
There should be no white space around images

**Comment by Niteshkr123** [comment]
Can you plz assign me this issue

**Comment by nathsagar24** [comment]
I would like to work on this issue. Can you please add CrossWoc & GSSOC21 labels and assign it to me?
