### ISSUE TITLE
Working app demo video⚒️

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#107]
Add a working app demo in the readme
Attach the video Related to it.

**Comment by Saransh-cpp** [comment]
Do you also want mockups like the one attached below or only a working video? Please let me know, thanks!


![threed_mockup](https://user-images.githubusercontent.com/74055102/107853888-69fabd80-6e3e-11eb-89ff-18aa544b8cd5.png)

**Comment by smaranjitghose** [comment]
> Do you also want mockups like the one attached below or only a working video? Please let me know, thanks!
> 
> ![threed_mockup](https://user-images.githubusercontent.com/74055102/107853888-69fabd80-6e3e-11eb-89ff-18aa544b8cd5.png)

Yes mockups are a necessity.

Along with that a short clip (perhaps converted into GIF) would be nice

**Comment by Saransh-cpp** [comment]
Okay thanks! I will start working on this.

**Comment by Saransh-cpp** [comment]
A question, do you want me to add the images and GIF in the repository or use the GitHub content link for making the app lighter?

**Comment by smaranjitghose** [comment]
Since you have already made the mockup, could you put the screens in a single image (as a grid). [Reference](https://github.com/smaranjitghose/girlscript_app).

**Comment by smaranjitghose** [comment]
> Since you have already made the mockup, could you put the screens in a single image (as a grid). [Reference](https://github.com/smaranjitghose/girlscript_app).

Keep the individual screen images too

**Comment by Saransh-cpp** [comment]
Will something like this work? I can do 4 screens at a time and then I can arrange two such images side by side in the README, please let me know.

![Google Pixel 4 XL Presentation](https://user-images.githubusercontent.com/74055102/108105180-4d66bb80-70b2-11eb-95c9-06fb00fc6f99.png)

**Comment by smaranjitghose** [comment]
> Will something like this work? I can do 4 screens at a time and then I can arrange two such images side by side in the README, please let me know.
> 
> ![Google Pixel 4 XL Presentation](https://user-images.githubusercontent.com/74055102/108105180-4d66bb80-70b2-11eb-95c9-06fb00fc6f99.png)

Perfect!
