### ISSUE TITLE
Add a GitHub action to auto-assign Mentors for every PR

### ISSUE THREAD

**Issue by m-code12** [smaranjitghose/DocLense#108]
I would like to add a GitHub action to auto-assign mentors for every PR. It sometimes becomes hectic for the mentors to take a look at all the Projects for the PRs made by the Contributors. This action would give a nice notification about reviewing the pr and make things pretty easy for the mentor. It would automatically ask for reviews by the mentors on every pr created.

Demo :
<img src="https://user-images.githubusercontent.com/1641039/78471193-71573200-776a-11ea-9b40-810c2d63270e.png">

**Comment by m-code12** [comment]
@anushbhatia @smaranjitghose Can I go ahead with this? I am a DWOC and MWOC participant.

**Comment by smaranjitghose** [comment]
> I would like to add a GitHub action to auto-assign mentors for every PR. It sometimes becomes hectic for the mentors to take a look at all the Projects for the PRs made by the Contributors. This action would give a nice notification about reviewing the pr and make things pretty easy for the mentor. It would automatically ask for reviews by the mentors on every pr created.
> 
> Demo :
> ![](https://user-images.githubusercontent.com/1641039/78471193-71573200-776a-11ea-9b40-810c2d63270e.png)

As far as the idea is concerned it is really nice given that the project had a lot maintainers. 

However, in reality, I and @anushbhatia are the only ones there and we already get notifications for each pr raised to an issue comment(for the repos we are watching).  And believe me, that's a lot of notifications! Having this would just increment the notifications
