### ISSUE TITLE
Onboarding screen Issue

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#124]
When a new user loads a new app this is the issue faced

https://user-images.githubusercontent.com/40017559/108641461-5fd36180-74c5-11eb-97e3-e35d8422b3b3.mp4

The onboarding screen is displayed everywhere in the app at every step. Either use a different plugin or resolve this issue

**Comment by Saransh-cpp** [comment]
I would like to work on this issue!
