### ISSUE TITLE
Settings Page features

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#138]
Reporting a bug functionality should work in the app.
Then we will move ahead with other ones.

**Comment by Saransh-cpp** [comment]
[Here](https://pub.dev/packages/instabug_flutter) is a great plugin for this feature. I am having some problems with implementing it but if anyone can do it or has some experience with it, go ahead. [(Instabug's website)](https://instabug.com/)

**Comment by anushbhatia** [comment]
Sure you can go ahead with this

**Comment by nicks101** [comment]
If this is under GSSOC21 and no one is assigned to it, can I work on this issue?

**Comment by arteevraina** [comment]
> If this is under GSSOC21 and no one is assigned to it, can I work on this issue?

Cool ! Let me assign it to you.

**Comment by arteevraina** [comment]
@anushbhatia Isn't this issue a part of GSSOC? If yes, I will add the label.

**Comment by smaranjitghose** [comment]
> @anushbhatia Isn't this issue a part of GSSOC? If yes, I will add the label.

All issues raised by us (and in the future raised by @arteevraina )are part of GSSOC . We didn't get time to add labels to the ones raised earlier😅

**Comment by arteevraina** [comment]
> > @anushbhatia Isn't this issue a part of GSSOC? If yes, I will add the label.
> 
> All issues raised by us (and in the future raised by @arteevraina )are part of GSSOC . We didn't get time to add labels to the ones raised earlier😅

Cool! 👀

**Comment by nicks101** [comment]
> [Here](https://pub.dev/packages/instabug_flutter) is a great plugin for this feature. I am having some problems with implementing it but if anyone can do it or has some experience with it, go ahead. [(Instabug's website)](https://instabug.com/)

Should I go with this? There are other options with null safety plugins also:
(Since we're using the latest flutter version, we can only add those packages that have null safety on, right?)

- [Wiredash](https://pub.dev/packages/wiredash)
- [Feedback](https://pub.dev/packages/feedback)

Couldn't find more.

**Comment by anushbhatia** [comment]
wire dash is pretty great and I recommend it too but I would like to have more opinion on it @Saransh-cpp @himanshusharma89 for it. How about this?

**Comment by Saransh-cpp** [comment]
> wire dash is pretty great and I recommend it too but I would like to have more opinion on it @Saransh-cpp @himanshusharma89 for it. How about this?

Yes, wire dash actually looks pretty good, integrating instabug with the project is weirdly hard and their GitHub repository isn't active much right now.

**Comment by nicks101** [comment]
Shall I work on wiredash then?
Also we'll need an account on [wiredash](https://wiredash.io/) (it has a free tier). 
From there create a project. Mainly I'll need the project id and secret key from wiredash settings of the project.
It all [here](https://pub.dev/packages/wiredash).

**Comment by himanshusharma89** [comment]
> wire dash is pretty great and I recommend it too but I would like to have more opinion on it @Saransh-cpp @himanshusharma89 for it. How about this?

Go for it, I'll implement it in the relic bazaar too.
