### ISSUE TITLE
Left Padding in Settings page

### ISSUE THREAD

**Issue by mohitsoni-dev** [smaranjitghose/DocLense#154]
There is no left padding in the text inside of gray text. Rest (right, top, bottom) padding is applied.
![3](https://user-images.githubusercontent.com/59525097/110483433-b8cf0680-810f-11eb-9dd6-2e72347a191d.jpg)

Also there is a lot of repeated code in settings.dart file which can be refactored.
I would love to work on this issue and I am a gssoc participant. Please assign me this task. Thanks.

**Comment by ritmojs** [comment]
I would like to work on this issue..

**Comment by arteevraina** [comment]
Hey @ritmojs! This has already been taken care in #155. You can have look on other open issues to work on :)
