### ISSUE TITLE
Add workflow using Github Actions

### ISSUE THREAD

**Issue by arteevraina** [smaranjitghose/DocLense#157]
Running CI tests before merging the PR will help to improve the code quality and will help to keep the code consistent across the files. 

WDYT @anushbhatia?

**Comment by anushbhatia** [comment]
we don't have CI/CD etup as of now but sure we can have it if you wish to create an issue for it.

**Comment by arteevraina** [comment]
Sure thing ! We can add label to this issue only.

**Comment by arteevraina** [comment]
closed by: #158
