### ISSUE TITLE
Refactoring deprecated widgets in Flutter 2.0

### ISSUE THREAD

**Issue by aayushbisen** [smaranjitghose/DocLense#159]
### Context

Some existing widgets like `FlatButton`, `RaisedButton` got deprecated in the latest iteration of Flutter. We can refactor the project to use the latest APIs provided by Flutter team in 2.0 version.

### Proposed Solution

Refactor deprecated widgets and methods and handle different warnings in the project.

> I'm participating in GSSOC21.

**Comment by anushbhatia** [comment]
Sure you can go ahead with it do mention the components modified in the code when you create a PR.
