### ISSUE TITLE
File names are not according to Dart preferences. 

### ISSUE THREAD

**Issue by SapinderSingh** [smaranjitghose/DocLense#160]
The source code file names are not according to Dart Preferences. And There is a lot of redundant code and imports. Can I fix them ?'
I am a participant of GSSOC 21

**Comment by arteevraina** [comment]
Sure thing! It will help to make the code more readable and better. Your PR is welcomed :)

**Comment by arteevraina** [comment]
But make sure to coordinate with @nicks101 as she is also working on Lint-related issues in order to avoid conflicts.

**Comment by nicks101** [comment]
hey @SapinderSingh, I'll leave the file name issue for now and resolve others.
@arteevraina is it okay if I open a PR with resolving all lint rules except file names?

**Comment by arteevraina** [comment]
Yes, feel free to open a PR.

**Comment by SapinderSingh** [comment]
@nicks101 Okay, Thanks.

**Comment by SapinderSingh** [comment]
Please add GSSOC 21 label to this issue.
