### ISSUE TITLE
Refactor project according to lint rules

### ISSUE THREAD

**Issue by nicks101** [smaranjitghose/DocLense#161]
This is related to issue #152 and PR #158 .

After adding lint rules, there are many problems (infos, warning) in the project. 
Most of them include :
- [prefer_const_constructors](https://dart-lang.github.io/linter/lints/prefer_const_constructors.html)
- [invalid_assignment](https://dart.dev/tools/diagnostic-messages#invalid_assignment)
- [argument_type_not_assignable](https://dart.dev/tools/diagnostic-messages#argument_type_not_assignable)
- [file_names](https://dart-lang.github.io/linter/lints/file_names.html)
- etc...

I'd like to resolve them.

**Comment by arteevraina** [comment]
Hi @nicks101! We definitely need to fix these warnings. Please go ahead with your PR.

**Comment by nicks101** [comment]
hey @arteevraina, can you please add GSSOC21 label to this issue?
