### ISSUE TITLE
Pixel Overflow in Bottom Toolbar

### ISSUE THREAD

**Issue by arteevraina** [smaranjitghose/DocLense#163]
### How to reproduce this?
 Just click the camera icon in the floating action buttons. After that when the picture opens up in the app you will see a bottom navigation toolbar.  See the pixels just overflowed in the toolbar.

### Screenshots
![Screenshot_2021-03-11-21-09-54-61](https://user-images.githubusercontent.com/43968121/110813742-cff82a80-82ae-11eb-9693-1ebea1055c01.jpg)

### Possible Fix:
Effective use of Media Queries.

### Device
Oppo A31

**Comment by 0xapurv** [comment]
I would like to work on this as a part of GSSoC'21, could you please assign it to me and guide me with the process?

**Comment by arteevraina** [comment]
Hey @believeInJha! Welcome to the repo. I have assigned you the issue. You can start working on this now. If you feel stuck just comment here. I will try to reply as soon as possible.

**Comment by 0xapurv** [comment]
Thanks for the opportunity @arteevraina , I will make it as soon as possible and send a PR.
