### ISSUE TITLE
Bug: Move to other directory feature is not working

### ISSUE THREAD

**Issue by Saransh-cpp** [smaranjitghose/DocLense#164]
The feature present in every PDF's card which performs the function of moving the PDF file to another location is not working, it does open up the screen to choose a directory and after choosing the directory, the console throws up an error that the file cannot be copied (Permission denied). I have looked up the Manifest file and all the permissions are provided, so right now I have no idea as to what is causing this error.

**Comment by aayushbisen** [comment]
Did you mean this button?

![image](https://user-images.githubusercontent.com/41341387/110900989-9f090b80-8329-11eb-9357-1e63fd0a23e0.png)

**Comment by Saransh-cpp** [comment]
Yes, clicking on that will lead you to the folder picker page. After landing there, click on the tick mark on the right side of any folder and you will see the console error.

**Comment by aayushbisen** [comment]
After clicking on that button the app gets navigated to a blank page for me. I didn't saw any folder pick page.

![0JqvKRtu3x](https://user-images.githubusercontent.com/41341387/110901892-03789a80-832b-11eb-8754-16951930a24a.gif)

**Comment by Saransh-cpp** [comment]
Ideally you should get a list of directories present in your device but this could be another potential bug, can you please check that if you actually have some directories in the emulator because this part is working fine on my side.

**Comment by aayushbisen** [comment]
Yes I have made a folder in emulator, still I am getting blank screen.

![Screenshot_1615532334](https://user-images.githubusercontent.com/41341387/110904418-f2318d00-832e-11eb-853f-cd5ce36c212e.png)

**Comment by aayushbisen** [comment]
Working on physical device.

**Comment by Saransh-cpp** [comment]
Then you can reproduce the bug on the physical device for now, I don't know why it is not working on the emulator for you.

**Comment by anushbhatia** [comment]
yep it isn't working on the emulator for me too
