### ISSUE TITLE
Improve Unit/Widget testing

### ISSUE THREAD

**Issue by arteevraina** [smaranjitghose/DocLense#171]
Idea is to contribute small widget/unit tests for the app. So, that we can achieve the aim of TDD for the project. Try to contribute a single test in a PR.

**Comment by Khushi-24** [comment]
@arteevraina Can I work on this?

**Comment by arteevraina** [comment]
Sure thing !

**Comment by smaranjitghose** [comment]
Any updates @Khushi-24 ?

**Comment by Khushi-24** [comment]
Sorry for the inconvenience. Due to some issues, I am unable to work on this.
