### ISSUE TITLE
Facing error on startup

### ISSUE THREAD

**Issue by arteevraina** [smaranjitghose/DocLense#175]
**Screenshot**

![Screenshot_2021-03-14-08-16-10-37_7294a262473530cafd6e94bd645d3149.jpg](https://user-images.githubusercontent.com/43968121/111055604-8ae61b00-849d-11eb-87c5-8f0d46f7f7dc.jpg)

**Comment by SapinderSingh** [comment]
@arteevraina I ran this app on my device. The issue on my device is different. #176

**Comment by arteevraina** [comment]
@SapinderSingh Can you share ss?

**Comment by SapinderSingh** [comment]
@arteevraina I have shared ss in #176

**Comment by Saransh-cpp** [comment]
@arteevraina, now that #176 is resolved, can you please uninstall the app once, pull the latest code and re-install it to check if this error still exists? because I am not able to reproduce this on my side.

**Comment by arteevraina** [comment]
ok @Saransh-cpp ! I will check it.

**Comment by arteevraina** [comment]
Fixed !
