### ISSUE TITLE
PopUp Menu in the top right of the app is not there.

### ISSUE THREAD

**Issue by SapinderSingh** [smaranjitghose/DocLense#177]
I want to create the PopUp Menu of the app as a participant of GSSOC 21.

**Comment by anushbhatia** [comment]
where do you want to do that please attach the image with labellings on it to get a better picture here?

**Comment by SapinderSingh** [comment]
![WhatsApp Image 2021-03-15 at 07 45 50](https://user-images.githubusercontent.com/29424616/111095009-85063d80-8562-11eb-9fe2-5e40808e1769.jpeg)

See the top right corner. I want to add a PopUp menu there.

**Comment by anushbhatia** [comment]
what popup menu will be added there?

**Comment by SapinderSingh** [comment]
@anushbhatia 

### A menu like this -
![pgwQh](https://user-images.githubusercontent.com/29424616/111119957-c877a080-8590-11eb-862d-0637a0771de2.png)

**Comment by anushbhatia** [comment]
This is not a priority as we don't have an option for login.
