### ISSUE TITLE
Minor bug in rating card dark mode

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#180]
![Screenshot_20210315_000706_com example doclense](https://user-images.githubusercontent.com/40017559/111080079-c24adb00-8522-11eb-9eb6-71379e721164.jpg)
Colour of. Submit button to be white.

**Comment by ghost** [comment]
@anushbhatia can you assign this to me?

**Comment by anushbhatia** [comment]
any update?

**Comment by adrishyantee** [comment]
Can I work on this? You can assign it to me.
I am new to flutter but I can do this change.

**Comment by surbhi2408** [comment]
Can you assign this to me.
I know how to do this.
I am GSSoC'21 participant.

**Comment by anushbhatia** [comment]
Sure @adrishyantee
