### ISSUE TITLE
Syntax Errors in ImageView.dart file

### ISSUE THREAD

**Issue by SapinderSingh** [smaranjitghose/DocLense#181]
There are syntax errors in ImageView.dart file. I want to work on this issue as a GSSOC 21 participant.

**Comment by SapinderSingh** [comment]
Please add GSSOC 21 label

**Comment by arteevraina** [comment]
What kind of syntax errors you were facing ?

**Comment by arteevraina** [comment]
Okay, Got it so there were brackets missing.

**Comment by SapinderSingh** [comment]
> Okay, Got it so there were brackets missing.

Yes Sir !!!

**Comment by smaranjitghose** [comment]
> Please add GSSOC 21 label

Please refrain from adding these comments related to labels in the issues. We have a github action for it or else the mentors would automatically add them.  I get notifications for all of these. Instead insure that your PRs are given the gssoc21 and the respective level tag.


In the PR description always write:

`Closes # issue_number` for it to work.

That being said, @SapinderSingh nice work finding out the bug.
