### ISSUE TITLE
Update Contributing.MD

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/DocLense#185]
[Reference](https://github.com/smaranjitghose/doc2pen/blob/master/CONTRIBUTING.md)

**Comment by tarunsinghofficial** [comment]
Hey @smaranjitghose can I work on this?

**Comment by payaldutta** [comment]
Hey, @smaranjitghose I am Payal from Nit, Kolkata, and a complete begineer in open source I choose this DocLense for the contribution I'm LGM-SOC'21 but stuck in as from where to start. I searched for good first issues but there are no such issues here and I am not getting the mailing list or contributor channel also. Can you please help me where should I start from and give me the mailing list also, so there I can ask for help and understand everything?
I Will be very grateful to you

**Comment by smaranjitghose** [comment]
@payaldutta Currently all the issues in this project assume you to have more than basic knowledge of Flutter+Dart. However, we would be soon opening issues regarding the web development related tasks. Keep an eye on the project. Meanwhile, check out doc2pen and awesome-porfolio-websites
