### ISSUE TITLE
Create an app icon

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#186]
Currently there are no app icon. We need to a new app icon svg files are there. If anything is needed do contact me.

**Comment by ShrutiJ-01** [comment]
If it is about adding a app Icon and not design related , I would like to work on it!

**Comment by anushbhatia** [comment]
Designing is not required

**Comment by abstrxtInfinity** [comment]
Since it is about just adding an icon, I would like to work on this.
GSSOC'21 participant.  If you would like please assign me this @anushbhatia.

**Comment by anujjain5699** [comment]
I would like to work on it, will u assign this issue to me @anushbhatia

**Comment by anushbhatia** [comment]
> Since it is about just adding an icon, I would like to work on this.
> GSSOC'21 participant. If you would like please assign me this @anushbhatia.

let him do this if he is not able to give the pr in 1 day u can take it up @anujjain5699

**Comment by abstrxtInfinity** [comment]
> > Since it is about just adding an icon, I would like to work on this.
> > GSSOC'21 participant. If you would like please assign me this @anushbhatia.
> 
> let him do this if he is not able to give the pr in 1 day u can take it up @anujjain5699

#### Can you tell me what will be the icon for the application.

**Comment by Udit-singh** [comment]
**@anushbhatia Can I add this image as an App icon under gssoc'21.**
![Screenshot (2548)](https://user-images.githubusercontent.com/55452299/113273165-00eddd00-92fa-11eb-8bc4-82eee09e8e9d.png)
**If yes, Then please assign it to me.**

**Comment by anushbhatia** [comment]
this looks fine to me but if you could remove the white background from it. Wouldn't that be better?

**Comment by anushbhatia** [comment]
> > > Since it is about just adding an icon, I would like to work on this.
> > > GSSOC'21 participant. If you would like please assign me this @anushbhatia.
> > 
> > 
> > let him do this if he is not able to give the pr in 1 day u can take it up @anujjain5699
> 
> #### Can you tell me what will be the icon for the application.

that's present in the assets folder.

**Comment by Udit-singh** [comment]
@anushbhatia I can remove the white background from it, Please assign it to me.

**Comment by Saransh-cpp** [comment]
> this looks fine to me but if you could remove the white background from it. Wouldn't that be better?

I think there was an SVG like this present in the assets folder. Maybe we can use that?

**Comment by anushbhatia** [comment]
> > this looks fine to me but if you could remove the white background from it. Wouldn't that be better?
> 
> I think there was an SVG like this present in the assets folder. Maybe we can use that?

yes

**Comment by anotherwebguy** [comment]
Plz assign me this issue i would like to create an app icon under gssoc

**Comment by anotherwebguy** [comment]
![SAVE_20210407_091423](https://user-images.githubusercontent.com/66346161/113807398-acc37c80-9781-11eb-951a-dd68f84b8214.jpg)
 Would this look nice?

**Comment by anotherwebguy** [comment]
![smart_doc_scanner_icon](https://user-images.githubusercontent.com/66346161/114161520-cad9da00-9945-11eb-8e17-374342a593ba.jpg)

Have a look at this @abstrxtInfinity @anushbhatia 
Will this do?

**Comment by anotherwebguy** [comment]
If this looks good i would make this as app icon and in the manifest file and make a pr?

**Comment by anotherwebguy** [comment]
> ![smart_doc_scanner_icon](https://user-images.githubusercontent.com/66346161/114161520-cad9da00-9945-11eb-8e17-374342a593ba.jpg)
> 
> Have a look at this @abstrxtInfinity @anushbhatia
> Will this do?

Should i make a pr? 
@anushbhatia @abstrxtInfinity

**Comment by anushbhatia** [comment]
We already have logo in assets folder.

**Comment by anotherwebguy** [comment]
> We already have logo in assets folder.

So what exactly i have to do? @anushbhatia

**Comment by anushbhatia** [comment]
https://github.com/smaranjitghose/DocLense/blob/main/assets/doclenselightsmall.svg
Add this logo to the project as app icon.

**Comment by anotherwebguy** [comment]
> https://github.com/smaranjitghose/DocLense/blob/main/assets/doclenselightsmall.svg
> Add this logo to the project as app icon.

Ok i'll make a pr soon. Thanks for assigning me :) @anushbhatia
