### ISSUE TITLE
Image isn't properly ratioed in GridItems

### ISSUE THREAD

**Issue by Alenjojo** [smaranjitghose/DocLense#189]
![WhatsApp Image 2021-03-16 at 7 38 52 PM](https://user-images.githubusercontent.com/51394913/111323385-d52eee00-868f-11eb-8eab-6f8ddcaeceee.jpeg)
If you can see from the above image , after taking all the photos to convert to pdf the page where it displays does not have proper ratioed image view function.

**Comment by Alenjojo** [comment]
If you consider this to be resoled can you assign this issue to me. If yes can you add the gssoc21 label too

**Comment by Alenjojo** [comment]
Shouldn't you guys be adding the lable too of gssoc21

**Comment by smaranjitghose** [comment]
> Shouldn't you guys be adding the lable too of gssoc21

Ya. I was expecting the github action to take care of it

**Comment by Alenjojo** [comment]
haha its alright. May i ask when im merging should i do anything in the issue part. Do i just have to merge it into a new branch.

**Comment by anushbhatia** [comment]
merge it in master only.
