### ISSUE TITLE
Settings Page: Contact Developers 

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#190]
Add an action to show the LinkedIn and GitHub profiles along with photos of
Smaranjit and Anush in the section
https://github.com/smaranjitghose/girlscript_app refer to the team page present here. 
![Screenshot_20210317_005612](https://user-images.githubusercontent.com/40017559/111368386-d4ac4c80-86bb-11eb-90c1-8e8059011497.jpg)
 

On click you can open a new page and add those features there.

**Comment by nicks101** [comment]
can I work on it?

**Comment by anushbhatia** [comment]
sure

**Comment by nicks101** [comment]
Can I get photos of developers that we have to display?

**Comment by nicks101** [comment]
This the basic layout. If you have UI in mind, do tell me. I'll make changes. Also, could I get images that we have to show?

![Screenshot_1615982325](https://user-images.githubusercontent.com/32807816/111464238-855f2e00-8746-11eb-877d-b23b3a719b5b.png)

**Comment by anushbhatia** [comment]
Add the icons to these rather than the links and images for the project can be taken from [here](https://github.com/smaranjitghose/doc2pen/tree/master/src/assets/images/team)
