### ISSUE TITLE
Settings Page: Add Contributors

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#191]
After issue #190 is completed using GitHub contributors API add all the contributors below the admins.
with their GitHub ids. 

if they want their LinkedIn to be added then wish to drop them to here.

**Comment by Saransh-cpp** [comment]
My [LinkedIn profile](https://www.linkedin.com/in/saransh-chopra-3a6ab11bb) :)

**Comment by nicks101** [comment]
[Here's](https://www.linkedin.com/in/nikki-goel-449563159/) mine.

**Comment by Udit-singh** [comment]
@anushbhatia Has of issue #190 is completed, I would like to work upon this under Gssoc'21,
Please assign it to me.
