### ISSUE TITLE
Adding a preview on home page

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#193]
Currently, there's no preview of pdf on the home page.
Add a small preview of the image there. Instead of the image icon present there.
![Screenshot_20210317_012454](https://user-images.githubusercontent.com/40017559/111371620-af214200-86bf-11eb-9abf-22a01f39f099.jpg)

**Comment by anushbhatia** [comment]
Expected
![Screenshot_20210317_013144_com adobe scan android](https://user-images.githubusercontent.com/40017559/111372365-8ea5b780-86c0-11eb-92a0-f355ef24cbed.jpg)

**Comment by Saransh-cpp** [comment]
I was working on this issue, I will make a PR!
