### ISSUE TITLE
Camera Based Scanner

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#2]
Camera Scanner Doesn't save images in the gallery.
Implementing the gallery function there

**Comment by Jahnavi-Jonnalagadda** [comment]
@anushbhatia @smaranjitghose I would like to work on this issue.

**Comment by anushbhatia** [comment]
Sure go on

**Comment by Jahnavi-Jonnalagadda** [comment]
@anushbhatia, should the captured images be saved in the app gallery or in device local storage? Could you please clarify?

**Comment by smaranjitghose** [comment]
> @anushbhatia, should the captured images be saved in the app gallery or in device local storage? Could you please clarify?

Local Device Storage
