### ISSUE TITLE
Package issue in  pubsec.yaml 

### ISSUE THREAD

**Issue by Borahb** [smaranjitghose/DocLense#201]
Package  package_info 2.0.0 requires SDK version >=2.12.0-259.9.beta <3.0.0 and no versions of package_info match >2.0.0 <3.0.0, package_info ^2.0.0 is forbidden.

So, because doclense depends on package_info ^2.0.0, version solving failed.
![Screenshot (457)](https://user-images.githubusercontent.com/49881148/111572291-58565e00-87ce-11eb-9ae4-07e08d9e2109.png)

Can I solve this issue?
#gssoc21

**Comment by anushbhatia** [comment]
Be careful while implementing backwards compatibility. The current versions should remain unaffected by this.

**Comment by Borahb** [comment]
okay
