### ISSUE TITLE
First Time App Launch Bug

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#210]
Opening an app on starting it carshes automatically as soon we click the option  to open the scanner camera. 
Redirect to the homepage at that time. 

https://user-images.githubusercontent.com/40017559/111689227-c6903480-8851-11eb-80ff-645f035aed17.mp4

**Comment by SamarpanCoder2002** [comment]
I think I can solve the problem..... After pick the image, app crashes right? I solved the problem in my project in a tricky way.....
If I can forward with that....please asssign me to here @anushbhatia I am also a GSSOC'21 participant

**Comment by SamarpanCoder2002** [comment]
Thanks for assign...I will made a pull request soon @anushbhatia

**Comment by SamarpanCoder2002** [comment]
@anushbhatia pull request added with video demo...kindly review it and merge it

**Comment by SamarpanCoder2002** [comment]
I modified some...please check it @anushbhatia

**Comment by SamarpanCoder2002** [comment]
I modified the code and now all checks passed... Kindly review it and merge it @anushbhatia

**Comment by SamarpanCoder2002** [comment]
You can check now @anushbhatia

**Comment by SamarpanCoder2002** [comment]
Now all the conflicts resolves and all lint checking are passes....Now you can review it and merge it @anushbhatia

**Comment by anushbhatia** [comment]
Great work @SamarpanCoder2002 🎊
