### ISSUE TITLE
Issue in pdf cards in dark theme.

### ISSUE THREAD

**Issue by abstrxtInfinity** [smaranjitghose/DocLense#221]
On toggling dark theme the color of the card text changes to white, I would like to mend it.
I have two ideas, either I just change the color of the text to black again, or I should change the color of the card to black in dark mode.
Kindly guide me what should be done.
GSSOC'21 participant
![bug](https://user-images.githubusercontent.com/55052738/111898069-b80c6d80-8a49-11eb-8f4e-3086c2e52413.jpeg)

**Comment by Saransh-cpp** [comment]
Please have a look at the issue #194 (Duplicate issues), that issue is assigned to someone but I don't think anyone is working on that, so you can comment there.
