### ISSUE TITLE
Starred pdf cards Right overflow.

### ISSUE THREAD

**Issue by abstrxtInfinity** [smaranjitghose/DocLense#223]
![error](https://user-images.githubusercontent.com/55052738/111903267-6d99e980-8a67-11eb-9ddc-a8d5d057e988.jpg)

Assign me this if not already fixed.
GSSOC'21 participant

**Comment by anushbhatia** [comment]
Add an option for three dots and add extra features on clicking that

**Comment by swarupbhc** [comment]
@anushbhatia I think this issue has been solved, you should close this issue.
