### ISSUE TITLE
Modifying/Styling Readme.md file by adding suitable emojis. 

### ISSUE THREAD

**Issue by DOOMSTERR** [smaranjitghose/DocLense#228]
## Request ✨
Hello sir, I want to modify the readme.md file.

## Detailed Description
I simply want to modify the heading by adding emojis and aligning the heading to the center:

### Heading to be modified:
-> Features: ----adding emojis
-> App Screens -----adding emojis/aligning to center
-> App Mock-ups -----adding emojis/aligning to center
-> App Demo(screen recording as well) -----adding emojis/aligning to center 
-> Code of Conduct -----adding emojis/aligning to center
-> License -----adding emojis/aligning to center
 
@anushbhatia & @smaranjitghose Sir, please allow me to do so, by assigning me the issue under the GSSOC21 label.

**Comment by anushbhatia** [comment]
Sure you can go ahead with this try giving PR as soon as possible.

**Comment by DOOMSTERR** [comment]
Sir, Please add the labels as well. Or else It won't be counted.
