### ISSUE TITLE
The three dotted vertical drop down icon in home page is not functional

### ISSUE THREAD

**Issue by adrishyantee** [smaranjitghose/DocLense#229]
The vertical pop-up menu which is supposed to be found after clicking on the rightmost icon on the homepage is not implemented. It should show us a list of items to be displayed there. Kindly look into it.

**Comment by Udit-singh** [comment]
@adrishyantee I would like to work upon this under gssoc21, one thing I want to ask, which List of items should be displayed?

**Comment by SapinderSingh** [comment]
@arteevraina Please assign this issue to me, as I raised it first. #177

**Comment by arteevraina** [comment]
> @arteevraina Please assign this issue to me, as I raised it first. #177 

@anushbhatia Do we need this ?

**Comment by anushbhatia** [comment]
> > @arteevraina Please assign this issue to me, as I raised it first. #177
> 
> @anushbhatia Do we need this ?

no we can remove that icon present. if anyone is ready to take that up create a new issue
