### ISSUE TITLE
Added google/facebook auth.

### ISSUE THREAD

**Issue by vinc3nati** [smaranjitghose/DocLense#231]
We can add authorization to our app, so that we can better manage our userbase and collect useful data.

**Comment by anushbhatia** [comment]
No use in a scanner.

**Comment by smaranjitghose** [comment]
> We can add authorization to our app, so that we can better manage our userbase and collect useful data.

TBH, we want the user experience of our app to be similar to what we ourselves want from the apps we use. Install, Get the job done, No Ads, No Tracking, Least Privacy Issues.
