### ISSUE TITLE
Removing three dot menu from the home screen.

### ISSUE THREAD

**Issue by SapinderSingh** [smaranjitghose/DocLense#232]
as @anushbhatia said, the app doesn't need that menu button. So I would like to remove that button. Please assign me this issue as a participant of GSSOC 21.

**Comment by smaranjitghose** [comment]
A quick tip: whenever you raise an issue that follows another previous issue or PR, it is more suitable to write something like "Continued from #issue_number" rather than "XYZ said this..so..."

Assigned for 2 days.
