### ISSUE TITLE
Enhancement: Using Named routes instead of on the fly routes.

### ISSUE THREAD

**Issue by SapinderSingh** [smaranjitghose/DocLense#244]
I think we should use named routes instead of on the fly routes. They are easy to manage and maintain. In the drawer, we should replace the pages instead of pop and push, because it makes the transition and animation look really bad. 

I want to solve this problem. Please assign me this issue, under GSSOC 21.

**Comment by anushbhatia** [comment]
can you mention the instances for it?

**Comment by SapinderSingh** [comment]
@anushbhatia what do you mean by instances ?

**Comment by anushbhatia** [comment]
where is fly routes being used any example?

**Comment by SapinderSingh** [comment]
@anushbhatia wherever Navigator.push is used.

**Comment by SapinderSingh** [comment]
@anushbhatia I think we should use the routes table and Navigator.pushNamed

**Comment by anushbhatia** [comment]
Be careful to check all navigation routes there

**Comment by SapinderSingh** [comment]
> Be careful to check all navigation routes there

@anushbhatia Okay 👍

**Comment by SapinderSingh** [comment]
Issue resolved by #248
