### ISSUE TITLE
Auto Label Issues

### ISSUE THREAD

**Issue by aishux** [smaranjitghose/DocLense#245]
**Describe the feature you'd like to add**
Add GitHub action to auto label issues with gssoc21 label when contributor asks to work under gssoc21. As it takes time for the maintainer to add labels, I can add a script that can auto-label issues with the GSSOC21 label whenever contributors ask to work under that label.

**Describe how you will do it**
I will add a script in .github folder which will automate the process.

**Additional context**
Please assign me this issue with a GSSOC tag and a level tag.

**Comment by smaranjitghose** [comment]
You wish to add a workflow for labelling PRs/Issues @aishux right?

**Comment by aishux** [comment]
Yes. So whenever someone opens an issue and asks to contribute under the GSSOC tag, the bot will assign them a GSSOC tag and a bug/feature/enhancement tag.

Attaching a screenshot for reference.

![image](https://user-images.githubusercontent.com/61228436/113342643-5a7ef780-934c-11eb-9fdd-19aaf5f339b2.png)

**Comment by smaranjitghose** [comment]
> Yes. So whenever someone opens an issue and asks to contribute under the GSSOC tag, the bot will assign them a GSSOC tag and a bug/feature/enhancement tag.
> 
> Attaching a screenshot for reference.
> 
> ![image](https://user-images.githubusercontent.com/61228436/113342643-5a7ef780-934c-11eb-9fdd-19aaf5f339b2.png)

Sure. I have it on some of my other repos too. Saves some time indeed. Go ahead with this please

**Comment by aishux** [comment]
Please assign me a level tag
