### ISSUE TITLE
Add 'Press back again to exit' functionality.

### ISSUE THREAD

**Issue by SapinderSingh** [smaranjitghose/DocLense#251]
To solve [this](https://github.com/smaranjitghose/DocLense/pull/248#pullrequestreview-631220987) issue, which @Saransh-cpp mentioned, I think the app should have a 'Press back again to exit' functionality. So that if use presses back on any screen, there will be a snackbar or a toast saying 'Press back again to exit' or something like that. 

If this issue approves, please assign it to me under GSSOC 21.

**Comment by anushbhatia** [comment]
create a pull request for this too along with this will merge both together.
