### ISSUE TITLE
Share the Document via Multiple Apps

### ISSUE THREAD

**Issue by SamarpanCoder2002** [smaranjitghose/DocLense#252]
Suppose some one scan a document and that store in storage...But If someone want to share it via whatsapp, or other social media app or save it in onedrive or in google drive, that feature till not added.....

I want to implement it... It's can gives the flexibility of the app...

I also a GSSOC21 participant...If I can forward with that, please assign me to here @anushbhatia

**Comment by anushbhatia** [comment]
Already added in-app drawer
