### ISSUE TITLE
Adding Loader✨

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#254]
Between screens where the loading time is more. It would be convenient to add a loader.
Loaders https://pub.dev/packages/flutter_easyloading you can use these or suggest some new package related to this.

Screen transition would feel better and UX will be improved by adding loader in the project.
YOu can refer to the `old_code` branch for the loader if you want references.

**Comment by SapinderSingh** [comment]
I would like to work on this issue.

**Comment by smaranjitghose** [comment]
> I would like to work on this issue.

Assigned for 2 days

**Comment by SapinderSingh** [comment]
@anushbhatia Can you specify the screens ?

**Comment by anushbhatia** [comment]
moving from every screen starting from the opening camera till the croping screen
