### ISSUE TITLE
Add play store logo to readme

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#263]
In the readme.MD add the logo mentioning the link for the play store and the redirection link is given below.
https://play.google.com/store/apps/details?id=com.anushbhatia.doclense

**Comment by SamikshaSankar** [comment]
Please assign this issue @anushbhatia

**Comment by Prakash-Haldar** [comment]
Please assign this issue to me sir @anushbhatia

**Comment by smaranjitghose** [comment]
@Prakash-Haldar please understand that simple issues once assigned to a participant won't be assigned to another before the completion of 3 days from the assignment date of the former

**Comment by Prakash-Haldar** [comment]
> @Prakash-Haldar please understand that simple issues once assigned to a participant won't be assigned to another before the completion of 3 days from the assignment date of the former

Ok Sir Thanks for the information

**Comment by Prakash-Haldar** [comment]
I will wait for my turn for sure. 
Thank You.

**Comment by SamikshaSankar** [comment]
![2021-06-11](https://user-images.githubusercontent.com/52104082/121582042-2ca0e800-ca4c-11eb-8003-b46b90245a7d.png)

Is this okay..?

**Comment by ayushvrma** [comment]
Please assign me this issue if it hasn't been completed yet.
