### ISSUE TITLE
Reducing the number of screen

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#266]
In the current Model
1. Two navigation screens are present
 one for cropping and one for filters.
 Instead, we can minimize it to one.
![WhatsApp Image 2021-05-21 at 12 40 45 AM (2)](https://user-images.githubusercontent.com/40017559/121140847-f13dc800-c857-11eb-857c-11823b7a9fff.jpeg)
![WhatsApp Image 2021-05-21 at 12 40 45 AM (3)](https://user-images.githubusercontent.com/40017559/121140903-01ee3e00-c858-11eb-8be5-f73b30410189.jpeg)

**Having both options on the same screen reduce the navigation part of it.**

**Comment by rudranshsharma123** [comment]
Hello, I am a participant of LGM-SOC. I am assuming all the widgets and logic from the Filters need to be transported into the main screen after taking the picture? I would love to work on this issue.

**Comment by anushbhatia** [comment]
> Hello, I am a participant of LGM-SOC. I am assuming all the widgets and logic from the Filters need to be transported into the main screen after taking the picture? I would love to work on this issue.

Yeah, the filter's button is present there you just have to move this here. If you face a problem with undo and redo function you can move it up.

**Comment by ayyysh04** [comment]
Already working on this task. Please assign this task to me.

**Comment by ayyysh04** [comment]
Done the task and created the pull request ,please review the same @anushbhatia

**Comment by ayyysh04** [comment]
> Done the task and created the pull request ,please review the same @anushbhatia

@smaranjitghose

**Comment by anushbhatia** [comment]
Sure will review it and let you know

**Comment by ayyysh04** [comment]
@anushbhatia you can close this issue now.😀
