### ISSUE TITLE
Option to provide flash while clicking pictures

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#268]
An option to enable to click pictures in flash.

**Comment by Priyanshu078** [comment]
please assign me this issue

**Comment by Priyanshu078** [comment]
sir In the app when we open the option to scan so it opens the phone camera and there is an option to use flash while scanning
so what to do

**Comment by Priyanshu078** [comment]
@anushbhatia please help

**Comment by anushbhatia** [comment]
Yes this has been resolved. You can create another if you find so.
