### ISSUE TITLE
Tile adjustment according to size of device

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#272]
In this case, you can see the tile feels really weird according to the size of the device.
**Solutions**
Reduce the size of the card.
Increase elements of the card according to the device
![Screenshot_20210612-154308](https://user-images.githubusercontent.com/40017559/121789692-8e508600-cbf5-11eb-9355-3e330c585a14.png)

**Comment by Priyanshu078** [comment]
@anushbhatia Sir I think this issue is also solved because it is working fine on my phone
![doclense3](https://user-images.githubusercontent.com/66347715/122569478-67b4a400-d068-11eb-966d-c47331284b2d.jpg)

**Comment by anushbhatia** [comment]
> @anushbhatia Sir I think this issue is also solved because it is working fine on my phone
> ![doclense3](https://user-images.githubusercontent.com/66347715/122569478-67b4a400-d068-11eb-966d-c47331284b2d.jpg)

Yep, but where the resolution of the screen is large this issue persists try a larger device like a tablet,iPad etc.

**Comment by Priyanshu078** [comment]
I want to work on this issue 
please assign me this issue @anushbhatia
