### ISSUE TITLE
Adding margin to right

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#273]
`Choose directory to save` is not any margin gap it is overflowing outside.
![Screenshot_20210612-154218](https://user-images.githubusercontent.com/40017559/121789780-7cbbae00-cbf6-11eb-97bc-cc5d02e61b45.png)
So add proper padding and margin so that text is not overflowing here.

**Comment by Priyanshu078** [comment]
please assign me this issue

**Comment by Priyanshu078** [comment]
Sir can we use the folder icon in place of Choose directory to save

**Comment by anushbhatia** [comment]
> Sir can we use the folder icon in place of Choose directory to save

You can add both by reducing the size of the text and adding an icon next to it.

**Comment by Priyanshu078** [comment]
Only with folder icon
![doclense1](https://user-images.githubusercontent.com/66347715/122211748-b1fd2000-cec4-11eb-8e30-f4a78a2054c6.jpg)

Text with folder icon
![doclense2](https://user-images.githubusercontent.com/66347715/122211803-c0e3d280-cec4-11eb-8298-7e95de9a0930.jpg)

please suggest

**Comment by anushbhatia** [comment]
> Only with folder icon
> ![doclense1](https://user-images.githubusercontent.com/66347715/122211748-b1fd2000-cec4-11eb-8e30-f4a78a2054c6.jpg)
> 
> Text with folder icon
> ![doclense2](https://user-images.githubusercontent.com/66347715/122211803-c0e3d280-cec4-11eb-8298-7e95de9a0930.jpg)
> 
> please suggest

folder looks better

**Comment by Priyanshu078** [comment]
so only folder will be ok

**Comment by shivangnayar-dev** [comment]
can i work on this

**Comment by jinosh05** [comment]
This issue was fixed so long so long ago, shall we close it
