### ISSUE TITLE
Image  box overflow

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#274]
Card box overflow's here to avoid this we can fit the image to the box.
![Screenshot_20210612-154118](https://user-images.githubusercontent.com/40017559/121789833-0c615c80-cbf7-11eb-93f0-a1f2cd2518c2.png)

**Comment by Priyanshu078** [comment]
@anushbhatia Is this issue solved because its working fine on my phone
![doc](https://user-images.githubusercontent.com/66347715/122570198-240e6a00-d069-11eb-968d-6d558ba032e0.jpg)

**Comment by anushbhatia** [comment]
> @anushbhatia Is this issue solved because its working fine on my phone
> ![doc](https://user-images.githubusercontent.com/66347715/122570198-240e6a00-d069-11eb-968d-6d558ba032e0.jpg)

Try using a tablet on an emulator?

**Comment by Priyanshu078** [comment]
Please assign me this issue 
I want to work on this issue @anushbhatia

**Comment by Atharv-Joshi** [comment]
![image](https://user-images.githubusercontent.com/53505850/142042685-66bdae32-9c85-4708-9c3e-8a8b934a8593.png)
On Phone 
![image](https://user-images.githubusercontent.com/53505850/142042750-cf7c8591-4208-4338-ab7e-eac9a57df1cb.png)
On emulator
![image](https://user-images.githubusercontent.com/53505850/142043217-74c683f7-7a68-45c0-9d34-3d6f2522ce92.png)


Is this solution ok?

**Comment by anushbhatia** [comment]
yes looks good

**Comment by Atharv-Joshi** [comment]
There is a UI update PR though so no point in doing this if its fixed in it
