### ISSUE TITLE
Error in Gallery page

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#282]
If I delete a pic, go back once, to the filters menu, and then go forward again, it adds the last clicked pic (+filter) to the pdf even though I don't want it. If you do this 3 times, it adds that pic 3 times to the pdf.

**Comment by ayyysh04** [comment]
so there are two problems:
1.when we add a image ,and then delete it and go back ,it shows the previous added image.
2.when we make a pdf or go back without creating a pdf ,in the next pdf our previously added image are also there.
right?

**Comment by anushbhatia** [comment]
Yes. Do you want work on them?

**Comment by ayyysh04** [comment]
ya sure, please assign this task to me

**Comment by ayyysh04** [comment]
Also while using the app ,I noticed that app UI is very outdated. If you allow me ,I can work on improving the UI of the app.

**Comment by ayyysh04** [comment]
> Also while using the app ,I noticed that app UI is very outdated. If you allow me ,I can work on improving the UI of the app too.

@anushbhatia

**Comment by ayyysh04** [comment]
> Yes. Do you want work on them?

ya sure, please assign this task to me

**Comment by ayyysh04** [comment]
Done the task and created the pull request ,please review the same @anushbhatia

**Comment by anushbhatia** [comment]
Will get back to you on this by tomorrow.
