### ISSUE TITLE
Camera is not opening if target sdk version >= 30

### ISSUE THREAD

**Issue by Niranjan-10** [smaranjitghose/DocLense#286]
![issue](https://user-images.githubusercontent.com/39689824/140602558-f9e2c3b4-3976-4035-987d-6ab7aca60c44.PNG)

**Comment by Niranjan-10** [comment]
Hey, there if you don't mind, I want to work on this issue.

**Comment by ayyysh04** [comment]
In my device, app is still crashing after camera is opened.

**Comment by jinosh05** [comment]
Hello there, I have worked on it and fixed the issue at my branch

https://github.com/jinosh05/DocLense
