### ISSUE TITLE
App need to be responsive

### ISSUE THREAD

**Issue by jinosh05** [smaranjitghose/DocLense#295]
When the app is installed in average size mobile, it works properly.

When installed on a Tab of high resolution or Low resolution mobile, the screen seems to show overflow error.

Someone recommend me any package to implement responsiveness to the app.

Thank you

**Comment by bornakpaul** [comment]
If this is still pending can you assign it to me ? @anushbhatia

**Comment by anushbhatia** [comment]
yes, it is still pending

**Comment by jinosh05** [comment]
I have completed the task now. I got free time now only. You can merge it now
