### ISSUE TITLE
Settings Page

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#3]
Add a setting page for adding
- reporting a bug
- request a feature
- contact developers

**Comment by Amit366** [comment]
I wan t to contribute to this.

**Comment by Amit366** [comment]
I want to contribute to this.

**Comment by himanshu007-creator** [comment]
please assign me this issue

**Comment by himanshu007-creator** [comment]
> please assign me this issue

sir job done.
https://github.com/smaranjitghose/DocLense/pull/18
![ss](https://user-images.githubusercontent.com/65963997/103368778-6d382500-4aee-11eb-99b7-7b9005d84cf3.png)

**Comment by yashsehgal** [comment]
Hey Can you assign me this issue?

**Comment by yashsehgal** [comment]
Thanks for assigning me this issue, I'll be sharing the design concepts soon. Also, What's the level of this issue?

**Comment by yashsehgal** [comment]
Hey @smaranjitghose, I wanna ask you a question. Do I have to use plain HTML and CSS to implement the design?

**Comment by yashsehgal** [comment]
> Hey @smaranjitghose, I wanna ask you a question. Do I have to use plain HTML and CSS to implement the design?

And How's this one? Shall I start with the UI design implementation?

**Comment by smaranjitghose** [comment]
> > Hey @smaranjitghose, I wanna ask you a question. Do I have to use plain HTML and CSS to implement the design?
> 
> And How's this one? Shall I start with the UI design implementation?

NO. This is a flutter project
