### ISSUE TITLE
Settings Page

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#34]
Implementing the setting page .

reporting a bug
request a feature
contact developers

**Comment by infiniteoverflow** [comment]
I would like to work on this as a part of DWOC. Can i get this issue assigned?

**Comment by niloysikdar** [comment]
I want to work on this issue , -- JWOC mentee .

**Comment by infiniteoverflow** [comment]
Are there any designs i should follow ?

**Comment by anushbhatia** [comment]
Nothing as of now but will give it if you want

**Comment by infiniteoverflow** [comment]
Yes , could use a reference

**Comment by anushbhatia** [comment]
![Screenshot_20210125_202912_com adobe scan android](https://user-images.githubusercontent.com/40017559/105723304-a37d8e80-5f4c-11eb-8bf9-cd50d2d4a060.jpg)

**Comment by infiniteoverflow** [comment]
Thanks
