### ISSUE TITLE
Implementing Search 

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#4]
Adding the feature of searching

**Comment by Vrushti24** [comment]
I wanted to contribute in this please guide me

**Comment by Sloth-Panda** [comment]
HEY, can I also get this issue?

**Comment by Vrushti24** [comment]
is it possible that after one week i will work on this issue because my exams are going to start on monday 4th jan ?? is it okk? @smaranjitghose

**Comment by smaranjitghose** [comment]
> is it possible that after one week i will work on this issue because my exams are going to start on monday 4th jan ?? is it okk? @smaranjitghose

In that case, I'll reassign you once your exams are over.

**Comment by Vrushti24** [comment]
Okay

**Comment by Vrushti24** [comment]
my exams will get over tomorrow so I will start working on this tomorrow . Is it okay?
@smaranjitghose

**Comment by smaranjitghose** [comment]
> my exams will get over tomorrow so I will start working on this tomorrow . Is it okay?
> @smaranjitghose

Sure

**Comment by Vrushti24** [comment]
PR #30 done please check it. @smaranjitghose 
and please add level tag

**Comment by Vrushti24** [comment]
hey @smaranjitghose I have been trying to solve the error but I am nit able to fix this I have been working on these long time any suggestions what should i do now?

**Comment by Vrushti24** [comment]
as u said I made a new PR #38  which is only code of search hope this works. @smaranjitghose

**Comment by Vrushti24** [comment]
And can u please add level tag thank u @smaranjitghose

**Comment by smaranjitghose** [comment]
> And can u please add level tag thank u @smaranjitghose

It will be counted via the PR

**Comment by Vrushti24** [comment]
Okay 👍

**Comment by Vrushti24** [comment]
@anushbhatia As u said I have added my file but in my pc I saw some strange error I guess there was some problem on my pc but I have added only my file as u said PR #39 .

**Comment by Vrushti24** [comment]
@anushbhatia can u merge this PR if its okay? PR #39

**Comment by Vrushti24** [comment]
PR #67 hope so works now I have attached screenshot of this
