### ISSUE TITLE
Suggestion And Features in App

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#42]
Feel free to add up any suggestion in the current project and add this here.

**Comment by Niteshkr123** [comment]
I would like to add an option of quick action. Whenever users will long-press the Doclence icon, they will get multiple options like home, about app, and setting. Clicking on that icon will redirect them directly to that screen

**Comment by anushbhatia** [comment]
Sure great idea go on

**Comment by Niteshkr123** [comment]
Thank you, Sir!
Please create a new issue of it and add a DWOC label. I Will address that issue :)

**Comment by smaranjitghose** [comment]
> Thank you, Sir!
> Please create a new issue of it and add a DWOC label. I Will address that issue :)

You can raise the issue yourself. We will add the label accordingly. Meanwhile, you can get started working on the PR

**Comment by Niteshkr123** [comment]
![Screenshot_2021-01-31-22-52-37-94_7294a262473530cafd6e94bd645d3149](https://user-images.githubusercontent.com/43056842/106392291-20aa7700-6417-11eb-89f9-47e4517e438a.png)


Sir I was exploring some parts of app and found there is pixel overflow in bottom. I want to raise and address this issue. Please allow me to do that

**Comment by smaranjitghose** [comment]
> ![Screenshot_2021-01-31-22-52-37-94_7294a262473530cafd6e94bd645d3149](https://user-images.githubusercontent.com/43056842/106392291-20aa7700-6417-11eb-89f9-47e4517e438a.png)
> 
> Sir I was exploring some parts of app and found there is pixel overflow in bottom. I want to raise and address this issue. Please allow me to do that

Sure fo ahead and raise an issue
