### ISSUE TITLE
Redesign App Drawer 

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#43]
Following the Colour Codes given in the readme.
Adding relevant icons to denote the particular section if you want.

**Comment by trupti123-sahu** [comment]
Sir , can u assign me this issue

**Comment by trupti123-sahu** [comment]
Sir can u help me
what type of enhancement is actually required  in drawer???

**Comment by smaranjitghose** [comment]
> Sir can u help me
> what type of enhancement is actually required in drawer???

@anushbhatia Can you help out with a mockup please
