### ISSUE TITLE
App taking long time to install in devices

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#44]
Working perfectly with the emulator but causing some issue to install in mobile as it takes a pretty long time to install.

**Comment by Niteshkr123** [comment]
I  think I can address this issue. I have been doing research on it, I found there are some minor mistakes in the dart file and also the debug show banner option is still visible even though it's false.
Can you please give me chance, because I have spent much time in understanding it

**Comment by anushbhatia** [comment]
Sure take a week for this
