### ISSUE TITLE
Having an Option to Save PDF to desired location

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#45]
Giving an option to save the pdf to the desired place.

**Comment by infiniteoverflow** [comment]
I would like to work on this issue.

**Comment by infiniteoverflow** [comment]
@anushbhatia I have a pending PR , i think i can work on this issue once it is merged , otherwise the changes i make might get conflicted with it as it is off the main branch.
Can you please have a look. Thank you.

**Comment by anushbhatia** [comment]
sure will do it now
