### ISSUE TITLE
Add a feature to rate the App 

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#46]
Adding a feature to give the star rating to the app.
Redirect to the user to Playstore as soon he finishes rating it in-app.

**Comment by Niteshkr123** [comment]
Can you please assign me this issue

**Comment by Niteshkr123** [comment]
Hello sir, I have solved this issue and it's PR has been merged successfully. Kindly add DWOC and level tag in my PR too.
