### ISSUE TITLE
Improve Docs 

### ISSUE THREAD

**Issue by Tejas-Ladhani** [smaranjitghose/DocLense#5]
Need to update the documentation . Unable to understand -what we need to achieve

**Comment by anushbhatia** [comment]
Sure go ahead with it

**Comment by Tejas-Ladhani** [comment]
okay

**Comment by smriti1313** [comment]
Hi,I would like to contribute in this too. Also as I read on devscript website, your project is included in projects given by DWOC but i see no label of DWOC on any of the issues. Kindly look into it and let me know. Thank you

**Comment by smaranjitghose** [comment]
> Hi,I would like to contribute in this too. Also as I read on devscript website, your project is included in projects given by DWOC but i see no label of DWOC on any of the issues. Kindly look into it and let me know. Thank you

Don't worry even at times the label is not there if you are assigned it just give me or @anushbhatia a reminder. We will definitely  update it😊
