### ISSUE TITLE
iOS Camera Access bug

### ISSUE THREAD

**Issue by infiniteoverflow** [smaranjitghose/DocLense#6]
**Issue :** The app crashes in iOS when someone clicks on the camera button. 

**Possible Solution :** We may have to add certain permissions in the `info.plist` file in the ios folder of the project.

**Comment by anushbhatia** [comment]
Sure I haven't added the file for it.

**Comment by infiniteoverflow** [comment]
Sure , I will work on that.

**Comment by anushbhatia** [comment]
is the bug resolved now

**Comment by infiniteoverflow** [comment]
Yes , it is resolved
