### ISSUE TITLE
Saved Documents in the Homepage

### ISSUE THREAD

**Issue by infiniteoverflow** [smaranjitghose/DocLense#62]
I would like to share my approach for showing the pdfs created by the user in the homepage as they open it :

- In the screen where we save the pdf after creating it, we can add the directory link to an object in shared_preferences. So every time a user creates a pdf, the link can be appended to it.
- We can retrieve the list of directories from shared_preferences in the homepage and show a list/grid view of the saved documents.

Maintainers kindly express your views on this approach. Thank you !!

**Comment by anushbhatia** [comment]
Sure go ahead with this

**Comment by smaranjitghose** [comment]
> I would like to share my approach for showing the pdfs created by the user in the homepage as they open it :
> 
> * In the screen where we save the pdf after creating it, we can add the directory link to an object in shared_preferences. So every time a user creates a pdf, the link can be appended to it.
> * We can retrieve the list of directories from shared_preferences in the homepage and show a list/grid view of the saved documents.
> 
> Maintainers kindly express your views on this approach. Thank you !!

Fantastic! Would love to see this

**Comment by infiniteoverflow** [comment]
Working on this ✌ , kind of slow due to exams , but will complete this asap.

**Comment by smaranjitghose** [comment]
> Working on this ✌ , kind of slow due to exams , but will complete this asap.

No worries, bro
I can understand
