### ISSUE TITLE
Feature: Implementing theme change option

### ISSUE THREAD

**Issue by Saransh-cpp** [smaranjitghose/DocLense#74]
This feature right now is not working in the app. I'd like to work on it as a part of MWoC and I was thinking of just giving the user a switch, to switch between 2 themes rather than a dropdown menu which is present in the app right now. Please give your inputs so I can start working on this. Thank you.

**Comment by anushbhatia** [comment]
Sure, settings page has this feature you can add this there

**Comment by Saransh-cpp** [comment]
@anushbhatia, I have been working on this feature and PR is going to be huge so can you please review and merge other pull requests which you intend to merge? as once I create this PR it will create a lot of conflicts.

**Comment by Saransh-cpp** [comment]
The feature is complete, here are some of the screens in both modes. Please review and accept my other PR so I can pull the code from the original repository, it will become very difficult for me to solve conflicts in this PR. Thank you so much:).

<img src="https://user-images.githubusercontent.com/74055102/107150903-11cb4380-6986-11eb-92d7-a41720f649ec.png" height="500"/>
<img src="https://user-images.githubusercontent.com/74055102/107150913-155eca80-6986-11eb-9577-dfd535875827.png"
height="500"/>
<img src="https://user-images.githubusercontent.com/74055102/107150914-15f76100-6986-11eb-88fd-9526135d3098.png"
height="500"/>
<img src="https://user-images.githubusercontent.com/74055102/107150909-13950700-6986-11eb-9f92-54e468d03ddf.png"
height="500"/>
<img src="https://user-images.githubusercontent.com/74055102/107150948-332c2f80-6986-11eb-872c-43995b3599db.png"
height="500"/>
<img src="https://user-images.githubusercontent.com/74055102/107150921-1859bb00-6986-11eb-9b88-a2397b6b8e75.png"
height="500"/>
<img src="https://user-images.githubusercontent.com/74055102/107150920-17c12480-6986-11eb-9f1c-301978935684.png"
height="500"/>
<img src="https://user-images.githubusercontent.com/74055102/107150918-17288e00-6986-11eb-899d-c2453774dc40.png"
height="500"/>
<img src="https://user-images.githubusercontent.com/74055102/107150946-31fb0280-6986-11eb-9a3b-3f47d5e53b09.png"
height="500"/>
