### ISSUE TITLE
Feature : Implement an Onboarding Screen for First Time Users

### ISSUE THREAD

**Issue by infiniteoverflow** [smaranjitghose/DocLense#77]
Onboarding screen could be something like this : https://pub.dev/packages/introduction_screen

We could show this particular screen to only those users who have opened the app for the first time, for others we could redirect them directly to the HomePage.

@smaranjitghose @anushbhatia Kindly express your views on this. Thank you !!

**Comment by smaranjitghose** [comment]
> Onboarding screen could be something like this : https://pub.dev/packages/introduction_screen
> 
> We could show this particular screen to only those users who have opened the app for the first time, for others we could redirect them directly to the HomePage.
> 
> @smaranjitghose @anushbhatia Kindly express your views on this. Thank you !!

Yes, we can go ahead with this!

**Comment by smaranjitghose** [comment]
@infiniteoverflow DocLense is also a part of IEEEDTU CWOC. If you wish do register for it as well so that you can benefit more from your valuable additions!

**Comment by infiniteoverflow** [comment]
Thanks @smaranjitghose , but actually im mentoring in CWOC with one of my projects too !!

**Comment by smaranjitghose** [comment]
> Thanks @smaranjitghose , but actually im mentoring in CWOC with one of my projects too !!

Oh. Cool
