### ISSUE TITLE
Implementing Search 

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#83]
To implement searching for a particular pdf

**Comment by Rukmini-Meda** [comment]
These issues can also be for cross winter of code right? Can I take them up as part of cwoc?

**Comment by anushbhatia** [comment]
yes

**Comment by smaranjitghose** [comment]
> These issues can also be for cross winter of code right? Can I take them up as part of cwoc?

All the issues are open for everyone irrespective of the program

**Comment by Rukmini-Meda** [comment]
Hello, I have been busy with my exams lately. I couldn't work on the task. I will unassign myself so that others can take this up.

**Comment by Saransh-cpp** [comment]
I would like to work on this issue!
