### ISSUE TITLE
Redesign App Drawer

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#84]
Following the Colour Codes given in the readme.
Adding relevant icons to denote the particular section if you want.

**Comment by anushbhatia** [comment]
![Screenshot_20210209_122703_com adobe scan android](https://user-images.githubusercontent.com/40017559/107326886-36cccd00-6ad2-11eb-81ca-12b3516e517e.jpg)
Instead of the profile we can use the logo rest the same design can be implemented

**Comment by Saransh-cpp** [comment]
I'd like to work on this issue. Only adding break lines and arranging the tiles in a group is required right?

**Comment by Saransh-cpp** [comment]
@anushbhatia I have attached a simple redesign of the drawer below, please let me know if you want any changes or I will open a PR. Also should I rename settings to preferences which is what appears in the app bar of settings screen.

![Screenshot_1613036767](https://user-images.githubusercontent.com/74055102/107621367-25bfbf80-6c7c-11eb-9807-7ea3fadee0c0.png)

**Comment by anushbhatia** [comment]
This looks great to me do give a pr soon for this
