### ISSUE TITLE
Feature : Migrate Local Storage to Hive

### ISSUE THREAD

**Issue by infiniteoverflow** [smaranjitghose/DocLense#85]
This feature will use the power of HiveDB. HiveDB is a NoSQL Local Storage for apps. We can implement Hive for the following cases where SharedPreferences are currently used : 

- Save the list of saved pdfs
- We can create a Preference class whose attributes will be the preferences users select like 'darkTheme' , etc and store it in the database. By this, it will be easier to access all the user preferences with just one class.

Maintainers kindly express your views on this.

**Comment by anushbhatia** [comment]
how is it better than firebase?

**Comment by infiniteoverflow** [comment]
We can of course use firebase for cloud storage.
We can use Hive for local storage which can be accessed offline where firebase needs internet connections.

And also we can use hive to store user preferences like theme (Dark or light) And other options that the user selects from the settings screen.

**Comment by anushbhatia** [comment]
Let me discuss with @smaranjitghose and let you know by today

**Comment by infiniteoverflow** [comment]
Sure. Thanks

**Comment by infiniteoverflow** [comment]
hii @anushbhatia  , any updates on this ?

**Comment by anushbhatia** [comment]
Sure go ahead with it will be great as the user won't need the internet for running of this and that's a great advantage

**Comment by infiniteoverflow** [comment]
Yes !! Thanks, I will get on with it.
