### ISSUE TITLE
Fix: Documentation 

### ISSUE THREAD

**Issue by souravseal99** [smaranjitghose/DocLense#86]
There were some typos in the documentation ( in README.md file, under the heading Contribution Guidelines).

- [ ] The link in point no 4 
- [ ] In point no 6, it's not mentioned that for this project the master branch is the main branch.
- [ ] There is a typo in point no 15.

**Comment by souravseal99** [comment]
If this is a valid issue, I would like to make a PR on this.
I have already made the necessary changes.

**Comment by anushbhatia** [comment]
Sure go ahead
