### ISSUE TITLE
Replacing all pngs with the svgs 👾

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#94]
You need to replace all png to svgs using flutter_svg plugin present in dart. If you are using any other method do mention that in comments before making a PR.

**Comment by Saransh-cpp** [comment]
I was trying to add the flutter_svg dependency in my fork but it shows
```
The current Flutter SDK version is 1.22.4.

Because doclense depends on flutter_svg >=0.19.2 which requires Flutter SDK version >=1.24.0-6.0.pre, version solving failed.
pub get failed (1; Because doclense depends on flutter_svg >=0.19.2 which requires Flutter SDK version >=1.24.0-6.0.pre, version solving failed.)
Process finished with exit code 1
```

I ran ```flutter upgrade``` after fixing some issues with flutter sdk on my device and it shows that flutter is already up to date. I guess the latest version of the plugin is only available on the beta channel of flutter.

I found a way around by using a previous version of flutter_svg. I hope that this won't be a problem for the app?

**Comment by anushbhatia** [comment]
No that won't be an issue will look through this and let you know the changes if any
