### ISSUE TITLE
Improving All the FAB buttons

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/DocLense#98]
Changing the colours of a button from green on the next step to another colour blue and white for that.
Currently, the button is not visible possible.
![image](https://user-images.githubusercontent.com/40017559/107606618-a7075a00-6c5c-11eb-884f-06831e9343cd.png)

Also, change the app bar of the about similar to the complete app.

**Comment by Saransh-cpp** [comment]
Can you please list all the improvements needed? The visibility issues of the buttons were solved in PR #81 and I pulled the main branch and checked again, the buttons are visible now!

**Comment by anushbhatia** [comment]
It is working perfectly in dark mode these improvements are in the light mode only.

**Comment by Saransh-cpp** [comment]
The icon in my device is white and I crosschecked with the main branch of the original repository, there is no color applied to the icon so I guess it should be picking up default color according to the theme constants. 


![Screenshot_1613037412](https://user-images.githubusercontent.com/74055102/107623020-b7303100-6c7e-11eb-9af9-2686158bb3a5.png)

**Comment by anushbhatia** [comment]
Yep i had not pulled the latest changes sorry for that
